services:

  db:
    image: postgres:15.3
    restart: always
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    tty: true
    command: >
        bash -c "python ./mymap/manage.py migrate
        && python ./mymap/manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"