services:

  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6543:5432"

  web:
    build: .
    tty: true
    command: python ./mymap/manage.py runserver 0.0.0.0:8000 --settings=mymap.settings.local
    restart: always
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"